name: Build arm64 image
on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build_and_push_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: baodn19
          password: ${{ secrets.GH_PAT }}

      - name: Build and push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/baodn19/go2:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/baodn19/go2:buildcache
          cache-to: type=registry,ref=ghcr.io/baodn19/go2:buildcache,mode=max,oci-mediatypes=true,image-manifest=true

      - name: Prune BuildKit cache
        run: docker buildx prune -af

      - name: Prune Docker
        run: docker system prune -af --volumes
