name: Build arm64 image

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build_and_push_arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: baodn19
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/baodn19/go2:latest
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
